<a href="https://colab.research.google.com/github/bpbpublications/Python-Powered-Excel/blob/main/Chapter%2001/Chapter_1_Maya's_Python_Workflow_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imporing Libraries

In [45]:
!pip install xlsxwriter

Requirement already satisfied: xlsxwriter in /usr/local/lib/python3.12/dist-packages (3.2.9)

In [46]:
import pandas as pd
import matplotlib.pyplot as plt
import xlsxwriter

# Reading and Combining Data Sets

In [47]:
# List of month file names (without extension)
months = ["YT_January", "YT_February", "YT_March", "YT_April", "YT_May", "YT_June"]

# Base GitHub URL

base_url = "https://raw.githubusercontent.com/bpbpublications/Python-Powered-Excel/main/Data/YT_month_wise/"

# Read and concat all files
df_all = pd.concat(
    [
        pd.read_excel(f"{base_url}{m}.xlsx")
        for m in months
    ],
    ignore_index=True
)

In [48]:
month_order = ['January', 'February', 'March', "April", "May", "June"]

df_all["month"] = pd.Categorical(df_all["month"],
                                 categories=month_order, ordered=True)

df_all

,title,playlist,duration_min,watch_min,views,impressions,subs_net,month
0,Common Excel Mistakes,Excel,11.5,89.92,1865,37801,21,January
1,Analyzing Survey Data in Excel,Excel,9.6,104.29,9191,42196,0,January
2,Advanced Excel Formulas,Excel,8.4,257.35,9202,35072,6,January
3,Excel Charts Masterclass,Excel,14.4,142.85,7994,24752,2,January
4,Excel for Data Analysis,Excel,4.1,213.92,4812,18685,3,January
...,...,...,...,...,...,...,...,...
73,2 Getting started with Google Colab |Python ID...,Python,16.0,417.68,3279,36111,34,June
74,Beautify your code with one click!,Python,6.0,123.65,5476,20541,12,June
75,3 B Probability Multiplication Rule,Statistics,23.0,123.92,3919,29921,12,June
76,5 Linear Transformation_1 Applications| Linear...,Linear Algebra,13.0,416.56,7739,17774,3,June
77,Tutorial_13| Functions Part4| Lambda function...,Python,11.0,349.34,749,45813,22,June

# Computing KPIs

In [49]:
df_all = (df_all
          .assign(
              watch_per_view = lambda df: df["watch_min"] / df["views"],
              click_thr_rate = lambda df: df["views"] / df["impressions"],
              subs_per_views = lambda df: df['subs_net']/df['views'],
              subs_per_imp = lambda df: df['subs_net']/df['impressions']
              ))

df_all

,title,playlist,duration_min,watch_min,views,impressions,subs_net,month,watch_per_view,click_thr_rate,subs_per_views,subs_per_imp
0,Common Excel Mistakes,Excel,11.5,89.92,1865,37801,21,January,0.048214,0.049337,0.011260,0.000556
1,Analyzing Survey Data in Excel,Excel,9.6,104.29,9191,42196,0,January,0.011347,0.217817,0.000000,0.000000
2,Advanced Excel Formulas,Excel,8.4,257.35,9202,35072,6,January,0.027967,0.262375,0.000652,0.000171
3,Excel Charts Masterclass,Excel,14.4,142.85,7994,24752,2,January,0.017870,0.322964,0.000250,0.000081
4,Excel for Data Analysis,Excel,4.1,213.92,4812,18685,3,January,0.044456,0.257533,0.000623,0.000161
...,...,...,...,...,...,...,...,...,...,...,...,...
73,2 Getting started with Google Colab |Python ID...,Python,16.0,417.68,3279,36111,34,June,0.127380,0.090803,0.010369,0.000942
74,Beautify your code with one click!,Python,6.0,123.65,5476,20541,12,June,0.022580,0.266589,0.002191,0.000584
75,3 B Probability Multiplication Rule,Statistics,23.0,123.92,3919,29921,12,June,0.031620,0.130978,0.003062,0.000401
76,5 Linear Transformation_1 Applications| Linear...,Linear Algebra,13.0,416.56,7739,17774,3,June,0.053826,0.435411,0.000388,0.000169
77,Tutorial_13| Functions Part4| Lambda function...,Python,11.0,349.34,749,45813,22,June,0.466409,0.016349,0.029372,0.000480

In [50]:
monthly_kpis = (df_all
                .groupby('month', observed=True)
                .agg(
                    total_views=("views", "sum"),
                    total_watch_min=("watch_min", "sum"),
                    avg_watch_per_view = ("watch_per_view", lambda x: round(x.mean(), 2)),
                    avg_duration_min=("duration_min", lambda x: round(x.mean(), 2)),
                    total_impressions=("impressions", "sum"),
                    avg_ctr = ("click_thr_rate", lambda x: round(x.mean(), 2)),
                    total_subs=("subs_net", "sum"),
                    total_subs_per_view = ('subs_per_views', 'sum'),
                    total_subs_per_imp = ('subs_per_imp', 'sum')
                )
                .reset_index())

monthly_kpis

,month,total_views,total_watch_min,avg_watch_per_view,avg_duration_min,total_impressions,avg_ctr,total_subs,total_subs_per_view,total_subs_per_imp
0,January,90947,3600.19,0.09,11.60,334054,0.72,712,0.212695,0.073965
1,February,65724,3470.98,0.07,12.22,213076,0.52,460,0.173959,0.042702
2,March,64913,3217.29,0.06,13.42,344088,0.42,484,0.089724,0.033577
3,April,83373,3540.27,0.05,16.27,451858,0.22,1233,0.221851,0.047764
4,May,71736,3160.69,0.07,14.58,321648,0.59,518,0.101502,0.035446
5,June,77630,3512.95,0.08,16.83,311457,0.45,260,0.068450,0.030780

In [51]:
playlist_kpis = (df_all
                .groupby('playlist', observed=True)
                .agg(
                    total_views=("views", "sum"),
                    total_watch_min=("watch_min", "sum"),
                    total_impressions=("impressions", "sum"),
                    avg_ctr = ("click_thr_rate", lambda x: round(x.mean(), 2))
                )
                .reset_index())

playlist_kpis

,playlist,total_views,total_watch_min,total_impressions,avg_ctr
0,Career Advice,7766,414.44,2341,3.32
1,Data Storytelling,9202,164.59,45623,0.20
2,Excel,229118,9005.21,943268,0.40
3,Linear Algebra,24559,1465.33,88277,0.37
4,Python,163620,8418.27,848236,0.47
5,Science Experiments,1960,206.99,2750,0.71
6,Statistics,18098,827.54,45686,0.97

# Creating Excel Report

In [52]:
last_month = df_all['month'].unique()[-1]
output_file = f"YouTube_Report_upto_{last_month}.xlsx"

with pd.ExcelWriter(output_file, engine="xlsxwriter") as writer:

    wb  = writer.book
    # Formats
    header_format = wb.add_format({"bold": True, "bg_color": "#D7E4BC"})
    title_format = wb.add_format({"bold": True, "font_size": 14, "align": "center", "valign": "vcenter", "bg_color": "#E0EBF5"})

    # --- Combined Data sheet ---
    df_all.to_excel(writer, sheet_name="Combined Data", index=False)

    ws_data = writer.sheets["Combined Data"]

    for col_num, value in enumerate(df_all.columns.values):
        ws_data.write(0, col_num, value, header_format)


    # --- KPIs sheet ---
    ws_kpis = writer.sheets['KPIs'] if 'KPIs' in writer.sheets else wb.add_worksheet('KPIs')

    ws_kpis.merge_range('A1:F1', 'Overall KPIs', title_format)

    # Calculate Overall KPIs
    overall_total_views = df_all['views'].sum()
    overall_avg_ctr = round(df_all['click_thr_rate'].mean(), 2)
    overall_avg_view_duration = round(df_all['duration_min'].mean(), 2)

    # Identify Top Performing Playlist
    top_playlist_row = playlist_kpis.loc[playlist_kpis['total_views'].idxmax()]
    top_playlist_name = top_playlist_row['playlist']
    top_playlist_views = top_playlist_row['total_views']
    top_playlist_watchtime = top_playlist_row['total_watch_min']

    headers = ['Total Views', 'Average CTR %', 'Average View Duration',
               'Top Performing Playlist', 'Top Playlist Views', 'Top Playlist Watchtime']
    ws_kpis.write_row(2, 0, headers, header_format)

    overall_kpis_values = [
        overall_total_views,
        overall_avg_ctr,
        overall_avg_view_duration,
        top_playlist_name,
        top_playlist_views,
        top_playlist_watchtime
    ]
    ws_kpis.write_row(3, 0, overall_kpis_values)

    # --- Monthly KPIs Table ---
    # Write title for Monthly KPIs
    ws_kpis.merge_range('A6:J6', 'Monthly KPIs', title_format)

    # Write monthly_kpis starting from row 8 (0-indexed 7) and col 1 (0-indexed 0)
    monthly_kpis.to_excel(writer, sheet_name="KPIs", startrow=7, startcol=0, index=False)

    # Apply header format for monthly_kpis (headers are in row 8, 0-indexed)
    for col_num, value in enumerate(monthly_kpis.columns.values):
        ws_kpis.write(7, col_num, value, header_format)

    # --- Playlist KPIs Table ---
    # Write title for Playlist KPIs
    ws_kpis.merge_range('L6:P6', 'Playlist KPIs', title_format) # L is col 11, P is col 15 (5 columns)

    # Write playlist_kpis starting from row 8 (0-indexed 2) and col L (0-indexed 11)
    playlist_kpis.to_excel(writer, sheet_name="KPIs", startrow=7, startcol=11, index=False)

    # Apply header format for playlist_kpis (headers are in row 2, 0-indexed)
    for col_num, value in enumerate(playlist_kpis.columns.values):
        ws_kpis.write(7, col_num + 11, value, header_format)

    # Optional: set column widths
    ws_data.autofit()
    ws_kpis.autofit()

    # --- Charts sheet ---
    ws_charts = wb.add_worksheet('Charts')

    # Create a new chart object for monthly data.
    chart_monthly = wb.add_chart({'type': 'line'})

    # Configure the chart series for monthly KPIs.
    max_row_monthly = len(monthly_kpis)

    chart_monthly.add_series({
        'name':       '=KPIs!$H$8',
        'categories': '=KPIs!$A$9:$A$' + str(8 + max_row_monthly),
        'values':     '=KPIs!$H$9:$H$' + str(8 + max_row_monthly),
        'marker':     {'type': 'automatic'},
    })

    chart_monthly.add_series({
        'name':       '=KPIs!$C$8',
        'categories': '=KPIs!$A$9:$A$' + str(8 + max_row_monthly),
        'values':     '=KPIs!$C$9:$C$' + str(8 + max_row_monthly),
        'marker':     {'type': 'automatic'},
    })

    # Add a chart title and some axis labels.
    chart_monthly.set_title({'name': 'Monthly Subscribers and Watch Time'})

    # Insert the chart into the worksheet.
    ws_charts.insert_chart('B2', chart_monthly)

    # Create a new chart object for playlist data.
    chart_playlist = wb.add_chart({'type': 'column'})

    # Configure the chart series for playlist KPIs.
    max_row_playlist = len(playlist_kpis)

    chart_playlist.add_series({
        'name':       '=KPIs!$N$8', # total_watch_min header (Col N, Row 8)
        'categories': '=KPIs!$L$9:$L$' + str(8 + max_row_playlist), # playlist names (Col L, Row 9 to end)
        'values':     '=KPIs!$N$9:$N$' + str(8 + max_row_playlist), # total_watch_min data (Col N, Row 9 to end)
    })



    # Add a chart title and some axis labels.
    chart_playlist.set_title({'name': 'Playlist Performance'})
    # chart_playlist.set_x_axis({'name': 'Playlist'})
    chart_playlist.set_y_axis({'name': 'Watch Time (Min)'})
    chart_playlist.set_legend({'none': True})

    # Insert the chart into the worksheet next to the monthly chart.
    ws_charts.insert_chart('J2', chart_playlist)


print(f"Excel report created: {output_file}")

Excel report created: YouTube_Report_upto_June.xlsx

# Downloading Report

In [53]:
from google.colab import files
files.download(output_file)
print(f"Excel report downloaded: {output_file}")

Excel report downloaded: YouTube_Report_upto_June.xlsx